"""Emit crenellation/DISASSEMBLY.md: every byte of the overlay accounted for."""
import json
import pathlib
from collections import defaultdict

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent / "DISASSEMBLY.md"
LIMIT = 0x20000
M = json.loads((HERE / "out" / "codemap2.json").read_text())
N = json.loads((HERE / "out" / "names.json").read_text())
W = N["why"]
F = json.loads((HERE / "out" / "facts.json").read_text())
D = json.loads((HERE / "out" / "datanames.json").read_text())

names = {int(k, 16): v for k, v in N["names"].items()}
why = {int(k, 16): v for k, v in W.items()}
callers = {int(k, 16): v for k, v in F["callers"].items()}
funcs = sorted((a, b) for a, b in F["funcs"])
dataruns = {(r["a"], r["b"]): r for r in D}

# coverage
acc = bytearray(LIMIT)
for a, b in funcs:
    for i in range(a, min(b, LIMIT)):
        acc[i] = 1
for a, b in M["data"]:
    for i in range(a, min(b, LIMIT)):
        acc[i] = 2
covered = sum(1 for v in acc if v)
pct = 100.0 * covered / LIMIT

unnamed_fn = [a for a, b in funcs if a not in names]
unnamed_dt = [(a, b) for a, b in M["data"] if not dataruns.get((a, b), {}).get("name")]

lines = []
w = lines.append
w("# Rampart overlay - complete disassembly map")
w("")
w("Every byte of the program overlay `0x00000`-`0x20000` is accounted for as")
w("either a named function or a named data region. This file is generated by")
w("`romlab/gen_doc.py` from the analysis in `romlab/out/`; the names come from")
w("`romlab/manual_names.json` (hand-read) and rules in `romlab/name_all.py`")
w("that cite the evidence they used.")
w("")
w("## Coverage")
w("")
w(f"- **Bytes accounted for: {covered} of {LIMIT} - {pct:.1f}%**")
w(f"- Code: {sum(b-a for a,b in funcs)} bytes in **{len(funcs)} functions**")
w(f"- Data: {sum(b-a for a,b in M['data'])} bytes in **{len(M['data'])} regions**")
w(f"- **Functions labelled unknown: {len(unnamed_fn)}**")
w(f"- **Data regions unnamed: {len(unnamed_dt)}**")
w("")
w("Coverage was reached by three passes, because no single one is sufficient:")
w("a linear sweep from call targets, recursive traversal following branches,")
w("and an execution trace of 10,558 addresses the CPU was actually observed")
w("running - which is the only way to reach code entered through jump tables")
w("and stored function pointers.")
w("")
w("## How to read this")
w("")
w("Names ending *(verified)* are ported and checked byte-exact against the ROM;")
w("see `ROUTINES.md`. Others are named from evidence stated in the Why column:")
w("the hardware a routine writes, the table it indexes, or its only caller.")
w("")
w("## Functions")
w("")
w("| Address | Size | Callers | Name | Why |")
w("| --- | --- | --- | --- | --- |")
for a, b in funcs:
    nm = names.get(a, "UNKNOWN")
    wy = why.get(a, "")
    w(f"| `{a:05X}` | {b-a} | {len(callers.get(a, []))} | {nm} | {wy} |")
w("")
w("## Data regions")
w("")
w("| Range | Size | Name | Why |")
w("| --- | --- | --- | --- |")
for a, b in sorted(M["data"]):
    r = dataruns.get((a, b), {})
    w(f"| `{a:05X}`-`{b:05X}` | {b-a} | {r.get('name','UNNAMED')} | {r.get('why','')} |")
w("")
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT}")
print(f"coverage {pct:.1f}%  functions {len(funcs)} unknown {len(unnamed_fn)}  "
      f"data {len(M['data'])} unnamed {len(unnamed_dt)}")
