"""Emit every ROM routine as TypeScript.

One file per address range so no single module is unmanageable, plus a dispatch
table so `call(addr, m)` reaches any routine - which is what the emitted jsr and
indirect jsr rely on.

Each function is a switch on the program counter. That is not the prettiest
shape, but it is the only one that handles branches backwards into the middle
of a routine, which the ROM does constantly.
"""
import json
import pathlib

import capstone

import m68kts

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent / "frontend" / "src" / "rom"
UP = (HERE / "prog_upper.bin").read_bytes()
md = capstone.Cs(capstone.CS_ARCH_M68K, capstone.CS_MODE_BIG_ENDIAN | capstone.CS_MODE_M68K_000)

BUCKETS = 12


def ident(name):
    out = []
    for ch in name:
        out.append(ch if ch.isalnum() else "_")
    s = "".join(out).strip("_")
    while "__" in s:
        s = s.replace("__", "_")
    return s or "routine"


def emit_function(entry, end, label):
    lines = []
    lines.append("/** %s */" % label.replace("*/", ""))
    # `at` lets the dispatcher enter part-way through: the ROM calls and jumps
    # into the middle of routines, and every address has a case already
    lines.append("export function fn_%05x(m: Machine, at = 0x%05x): void {"
                 % (entry, entry))
    lines.append("  let pc = at;")
    lines.append("  for (;;) {")
    lines.append("    m.tick();")
    lines.append("    switch (pc) {")
    addr = entry
    while addr < end:
        ins = next(md.disasm(UP[addr:addr + 16], addr, 1), None)
        if ins is None:
            addr += 2
            continue
        nxt = addr + ins.size
        try:
            body = m68kts.emit(ins, nxt)
        except Exception as exc:  # noqa: BLE001 - the emitter must never abort a build
            body = None
        if body is None:
            body = ("throw new Error('unsupported %s %s at 0x%05x');"
                    % (ins.mnemonic, (ins.op_str or "").replace("'", ""), addr))
        lines.append("      case 0x%05x: { %s } break;" % (addr, body))
        addr = nxt
    # Falling out of a routine's range is normal: the boundaries come from call
    # targets, so a "routine" is often a label inside a longer stretch of code
    # that simply runs on. Continue in whichever routine covers the address.
    lines.append("      default: call(pc, m); return;")
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    facts = json.loads((HERE / "out" / "facts.json").read_text())
    names = json.loads((HERE / "out" / "names.json").read_text())["names"]
    funcs = sorted((a, b) for a, b in facts["funcs"])
    label = {int(k, 16): v for k, v in names.items()}

    per = (len(funcs) + BUCKETS - 1) // BUCKETS
    written = []
    for i in range(BUCKETS):
        chunk = funcs[i * per:(i + 1) * per]
        if not chunk:
            continue
        path = OUT / ("routines%02d.ts" % i)
        body = ["// Generated by romlab/gen_ts.py - do not edit by hand.",
                "// Routines 0x%05x - 0x%05x of the Rampart program overlay."
                % (chunk[0][0], chunk[-1][1]),
                "",
                "import type { Machine } from './machine';",
                "import { call } from './dispatch';",
                ""]
        for a, b in chunk:
            body.append(emit_function(a, b, label.get(a, "routine")))
            body.append("")
        path.write_text("\n".join(body), encoding="utf-8")
        written.append((path.name, len(chunk)))

    # dispatch table: address -> routine
    d = ["// Generated by romlab/gen_ts.py - do not edit by hand.",
         "import type { Machine } from './machine';"]
    for i, (fname, _) in enumerate(written):
        d.append("import * as r%02d from './%s';" % (i, fname[:-3]))
    d.append("")
    d.append("type Routine = (m: Machine, at?: number) => void;")
    d.append("")
    d.append("/** Routine entry addresses, ascending, with their functions. */")
    d.append("const STARTS: number[] = [")
    idx = 0
    starts = []
    for i in range(BUCKETS):
        chunk = funcs[i * per:(i + 1) * per]
        if not chunk:
            continue
        for a, b in chunk:
            starts.append((a, b, idx))
        idx += 1
    starts.sort()
    for a, _, _ in starts:
        d.append("  0x%05x," % a)
    d.append("];")
    d.append("const ENDS: number[] = [")
    for _, b, _ in starts:
        d.append("  0x%05x," % b)
    d.append("];")
    d.append("const FNS: Routine[] = [")
    for a, _, bucket in starts:
        d.append("  r%02d.fn_%05x," % (bucket, a))
    d.append("];")
    d.append("")
    d.append("/**")
    d.append(" * Call by ROM address. The address need not be a routine's first")
    d.append(" * instruction: the ROM jumps into the middle of routines, so this finds")
    d.append(" * the routine containing the address and enters it there.")
    d.append(" */")
    d.append("export function call(addr: number, m: Machine): void {")
    d.append("  const a = addr >>> 0;")
    d.append("  let lo = 0;")
    d.append("  let hi = STARTS.length - 1;")
    d.append("  let found = -1;")
    d.append("  while (lo <= hi) {")
    d.append("    const mid = (lo + hi) >> 1;")
    d.append("    if (STARTS[mid] <= a) { found = mid; lo = mid + 1; } else { hi = mid - 1; }")
    d.append("  }")
    d.append("  if (found < 0 || a >= ENDS[found]) {")
    d.append("    if (m.stubMissing) { m.missingCalls.push(a); return; }")
    d.append("    throw new Error('no routine covers 0x' + a.toString(16));")
    d.append("  }")
    d.append("  FNS[found](m, a);")
    d.append("}")
    d.append("")
    d.append("export const ROUTINE_COUNT = %d;" % len(funcs))
    (OUT / "dispatch.ts").write_text("\n".join(d), encoding="utf-8")

    total = sum(n for _, n in written)
    print("routines emitted: %d across %d files" % (total, len(written)))
    for n, c in written:
        print("   %-16s %d" % (n, c))


if __name__ == "__main__":
    main()
