"""Emit a TypeScript function per instruction encoding, using the same rules.

This is the translator under test, applied to one instruction at a time. If a
rule is wrong it shows up here as itself, instead of being smeared across every
routine that happens to use it.
"""
import pathlib

import capstone

import m68kts

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent / "frontend" / "src" / "rom"
CODE = 0x3E6000
md = capstone.Cs(capstone.CS_ARCH_M68K, capstone.CS_MODE_BIG_ENDIAN | capstone.CS_MODE_M68K_000)


def main():
    lines = ["// Generated by romlab/gen_insn.py - do not edit by hand.",
             "// One function per instruction encoding, emitted by the same rules",
             "// the routine translator uses, so a failure names the rule.",
             "",
             "import type { Machine } from './machine';",
             "",
             "type Runner = (m: Machine) => void;",
             "",
             "const TABLE: Record<string, Runner> = {"]
    n = skipped = 0
    for raw in (HERE / "out" / "insn" / "encodings.txt").read_text().splitlines():
        parts = raw.split("  ", 1)
        if not parts or len(parts[0]) < 4:
            continue
        hexs = parts[0].strip()
        data = bytes.fromhex(hexs)
        ins = next(md.disasm(data, CODE, 1), None)
        if ins is None:
            skipped += 1
            continue
        try:
            body = m68kts.emit(ins, CODE + ins.size)
        except Exception:
            body = None
        if body is None:
            skipped += 1
            continue
        # the emitted form assigns pc and may call; neither applies to a single
        # instruction, so strip the pc assignment and refuse anything that calls
        if "call(" in body:
            skipped += 1
            continue
        body = body.replace("pc = 0x%05x;" % (CODE + ins.size), "")
        lines.append("  '%s': (m) => { let pc = 0; void pc; %s }," % (hexs, body.strip()))
        n += 1
    lines.append("};")
    lines.append("")
    lines.append("/** Run one encoding through the translator's rules. */")
    lines.append("export function runOne(m: Machine, at: number): void {")
    lines.append("  let hex = '';")
    lines.append("  for (let i = 0; i < 8; i += 1) {")
    lines.append("    hex += m.byte(at + i).toString(16).toUpperCase().padStart(2, '0');")
    lines.append("  }")
    lines.append("  for (let len = 8; len >= 2; len -= 1) {")
    lines.append("    const f = TABLE[hex.slice(0, len * 2)];")
    lines.append("    if (f) { f(m); return; }")
    lines.append("  }")
    lines.append("  throw new Error('no rule for encoding ' + hex);")
    lines.append("}")
    (OUT / "insn-run.ts").write_text("\n".join(lines), encoding="utf-8")
    print("encodings emitted: %d   skipped (branch, call or no rule): %d" % (n, skipped))


if __name__ == "__main__":
    main()
