// Runtime loader for the Track 5 sprite atlas (generated by
// scripts/generate-sprites.mjs). Fetches the manifest + sheet textures and hands
// back per-frame Pixi Textures the boards draw as Sprites. Everything is
// best-effort: any failure returns null so SkirmishBoard/EditorBoard fall back
// to their Graphics primitives and the game still renders.

import { Assets, Rectangle, Texture } from 'pixi.js';

interface Frame { x: number; y: number; w: number; h: number }
interface Layer { image: string; image2x: string; w: number; h: number; cellW: number; cellH: number; anchor?: { x: number; y: number }; frames: Record<string, Frame> }
interface Manifest { version: number; tile: Layer; piece: Layer }

export interface SpriteAtlas {
  tile(terrain: string): Texture | null;
  /** Falls back to the neutral frame (rocks) when no side-specific frame exists. */
  piece(side: string, type: string): Texture | null;
  pieceAnchor: { x: number; y: number };
  tileCell: { w: number; h: number };
}

function slice(base: Texture, layer: Layer): Record<string, Texture> {
  const out: Record<string, Texture> = {};
  for (const [key, f] of Object.entries(layer.frames)) {
    out[key] = new Texture({ source: base.source, frame: new Rectangle(f.x, f.y, f.w, f.h) });
  }
  return out;
}

/**
 * Load the atlas. `base` lets callers/tests point at a different origin; defaults
 * to the site root. Returns null (never throws) if the manifest or either sheet
 * cannot be loaded, so callers can branch to a Graphics fallback.
 */
export async function loadSpriteAtlas(base = ''): Promise<SpriteAtlas | null> {
  try {
    const res = await fetch(`${base}/assets/sprites/atlas.json`);
    if (!res.ok) return null;
    const m = (await res.json()) as Manifest;
    if (!m?.tile?.frames || !m?.piece?.frames) return null;

    const [tileTex, pieceTex] = await Promise.all([
      Assets.load(`${base}${m.tile.image}`) as Promise<Texture>,
      Assets.load(`${base}${m.piece.image}`) as Promise<Texture>,
    ]);
    // Nearest-neighbour keeps the pixel art crisp at any board scale.
    tileTex.source.scaleMode = 'nearest';
    pieceTex.source.scaleMode = 'nearest';

    const tiles = slice(tileTex, m.tile);
    const pieces = slice(pieceTex, m.piece);
    return {
      tile: (terrain) => tiles[terrain] ?? null,
      piece: (side, type) => pieces[`${side}.${type}`] ?? pieces[`neutral.${type}`] ?? null,
      pieceAnchor: m.piece.anchor ?? { x: 0.5, y: 0.75 },
      tileCell: { w: m.tile.cellW, h: m.tile.cellH },
    };
  } catch {
    return null;
  }
}
