// Generated by romlab/decomp.py - do not edit by hand.
//
// Decompiled routines: recovered source, not transliterated machine code.
// Stack arguments have become parameters and registers have become expressions.
// Every function here is checked against the recompiled routine at the same
// address by decomp.test.ts, on random machine states, and none of it is
// trusted without that.

import type { Machine } from './machine';

let M: Machine;
/** Point the decompiled code at a machine before calling anything. */
export function bind(m: Machine): void { M = m; }

const load8 = (a: number): number => M.byte(a);
const load16 = (a: number): number => M.load(a, 16);
const load32 = (a: number): number => M.load(a, 32);
const store8 = (a: number, v: number): void => M.setByte(a, v);
const store16 = (a: number, v: number): void => M.store(a, v, 16);
const store32 = (a: number, v: number): void => M.store(a, v, 32);
/** A result the caller reads out of a register. These become ordinary return
 *  values once the call sites are lifted too; for now they go back where the
 *  ROM's caller expects to find them. */
const setReg = (r: string, v: number): void => {
  (M as unknown as Record<string, number>)[r] = v;
};
void load8; void load16; void load32; void store8; void store16; void store32; void setReg;


export function fn_0052a(): void {
  store16(0x3e0802, 0x0);
}

export function fn_00618(): void {
  store8(0x72ffff, 0);
}

export function fn_0156c(d0: number, arg0: number): void {
  const t0 = ((d0 & 0xffff0000) | (arg0 & 0xffff));
  store16(0x3e0dc8, (load16(0x3e0dc8) | (t0 & 0xffff)));
  setReg('d0', t0);
}

export function fn_01578(d0: number, arg0: number): void {
  const t0 = ((d0 & 0xffff0000) | (arg0 & 0xffff));
  store16(0x3e0dc6, (load16(0x3e0dc6) | (t0 & 0xffff)));
  setReg('d0', t0);
}

export function fn_015b4(): void {
  store8(0x3e1ae2, 0xff);
}

export function fn_015be(arg0: number): void {
  store32(arg0 + 0x4, 0);
  store8(arg0 + 0x1d, 0);
  store8(arg0 + 0x19, 0);
  store8(arg0 + 0x21, 0x5);
  setReg('a0', arg0);
}

export function fn_019d8(arg0: number): void {
  const t0 = load32(arg0 + 0x5e);
  store16(t0, 0x28);
  const t1 = load32(arg0 + 0x62);
  store16(t1, 0x28);
  setReg('a0', t1);
  setReg('a1', arg0);
}

export function fn_03726(): void {
  // nothing observable
}

export function fn_03f10(): void {
  store8(0x3e0e78, 0x1);
}

export function fn_03f1a(): void {
  store8(0x3e0e78, 0);
}

export function fn_05cb0(d0: number, d1: number, arg0: number, arg1: number): void {
  const t0 = ((d0 & 0xffff0000) | (arg1 & 0xffff));
  const t1 = load16(arg0 + 0xc);
  const t2 = ((d1 & 0xffff0000) | (t1 & 0xffff));
  const t3 = ((t2 & 0xffff) & 0xfff0);
  const t4 = ((t2 & 0xffff0000) | (t3 & 0xffff));
  const t5 = ((t4 & 0xffff) + (t0 & 0xffff));
  const t6 = ((t4 & 0xffff0000) | (t5 & 0xffff));
  store16(arg0 + 0xc, (t6 & 0xffff));
  store8(arg0 + 0x2, (load8(arg0 + 0x2) | 0x20));
  setReg('a0', arg0);
  setReg('d0', t0);
  setReg('d1', t6);
}

export function fn_05dea(): void {
  // nothing observable
}

export function fn_05dfe(): void {
  // nothing observable
}

export function fn_05e00(): void {
  // nothing observable
}

export function fn_05e02(arg0: number): void {
  setReg('d0', arg0);
}

export function fn_05e08(): void {
  // nothing observable
}

export function fn_0663c(): void {
  store32(0x3e209c, (load32(0x3e209c) + 0x2));
  const t0 = load32(0x3e209c);
  setReg('a0', 0x3e209c);
  setReg('d0', t0);
}

export function fn_0a7e4(): void {
  // nothing observable
}

export function fn_0c4e8(arg0: number): void {
  const t0 = load32(arg0);
  store32(t0 + 0x4, load32(arg0 + 0x4));
  const t1 = load32(arg0 + 0x4);
  store32(t1, load32(arg0));
  store32(arg0 + 0x4, 0x0);
  store32(arg0, 0x0);
  setReg('a0', arg0);
  setReg('a1', t1);
  setReg('d0', 0x0);
}

export function fn_0db66(arg0: number): void {
  setReg('d0', arg0);
}

export function fn_0db6c(arg0: number): void {
  setReg('d0', arg0);
}

export function fn_0db72(arg0: number): void {
  setReg('d0', arg0);
}

export function fn_0db78(arg0: number): void {
  setReg('d0', arg0);
}

export function fn_0ee3a(): void {
  store16(0x3e1cf4, 0xffff);
}

export function fn_0f2ee(arg0: number): void {
  const t0 = (arg0 + 0x1f7f0);
  setReg('d0', t0);
}

export function fn_0f2fa(arg0: number): void {
  const t0 = (arg0 - 0x1f7f0);
  setReg('d0', t0);
}

export function fn_0fc0e(): void {
  // nothing observable
}

export function fn_1354c(): void {
  store16(0x3e3f00, 0x9);
  store16((0x3e3f00 + 2), 0xd);
  store16(((0x3e3f00 + 2) + 2), 0xa);
  store16((((0x3e3f00 + 2) + 2) + 2), 0xe);
  store16(0x3e3f08, 0x5b95);
  store16(0x3e3f0a, 0x1016);
  store16(0x3e3f0c, 0xb087);
  setReg('a0', ((((0x3e3f00 + 2) + 2) + 2) + 2));
}

export function fn_193f2(arg0: number, arg1: number, arg2: number): void {
  store8(arg0, arg1);
  store8((arg0 + 1), arg2);
  store8(((arg0 + 1) + 1) + 0x4, 0);
  setReg('a0', ((arg0 + 1) + 1));
}

export function fn_1b11c(d0: number, arg0: number): void {
  const t0 = (arg0 + 0x1e0000);
  store8(0x3e3d6c, 0x7);
  const t1 = ((d0 & 0xffff0000) | (0 & 0xffff));
  store16(0x3e3d78, (t1 & 0xffff));
  store16(0x3e3d76, (t1 & 0xffff));
  store16(0x3e3d74, (t1 & 0xffff));
  store16(0x3e3d72, (t1 & 0xffff));
  const t2 = load16(0x3e3d8e);
  const t3 = ((0x0 & 0xffff0000) | (t2 & 0xffff));
  const t4 = (t3 & 0xffef);
  store16(t0, (t4 & 0xffff));
  store16(0x3e3d8e, (load16(0x3e3d8e) | 0x10));
  store16(0x3e3d8e, (load16(0x3e3d8e) | 0x400));
  store16(t0, load16(0x3e3d8e));
  setReg('a0', t0);
  setReg('a1', 0x3e3d8e);
  setReg('d0', t4);
}

/** Where each routine's parameters come from - the 68000 has no

 *  fixed calling convention, and this code uses registers and the

 *  stack, sometimes in the same routine. */

export type ParamSource = { from: 'reg'; name: string } | { from: 'stack'; off: number };



/** Every decompiled routine, by the ROM address it came from. */

export const DECOMPILED: ReadonlyArray<{

  at: number; fn: (...a: number[]) => void; params: ParamSource[];

}> = [

  { at: 0x0052a, fn: fn_0052a as (...a: number[]) => void, params: [] },

  { at: 0x00618, fn: fn_00618 as (...a: number[]) => void, params: [] },

  { at: 0x0156c, fn: fn_0156c as (...a: number[]) => void, params: [{ from: 'reg', name: 'd0' }, { from: 'stack', off: 6 }] },

  { at: 0x01578, fn: fn_01578 as (...a: number[]) => void, params: [{ from: 'reg', name: 'd0' }, { from: 'stack', off: 6 }] },

  { at: 0x015b4, fn: fn_015b4 as (...a: number[]) => void, params: [] },

  { at: 0x015be, fn: fn_015be as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x019d8, fn: fn_019d8 as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x03726, fn: fn_03726 as (...a: number[]) => void, params: [] },

  { at: 0x03f10, fn: fn_03f10 as (...a: number[]) => void, params: [] },

  { at: 0x03f1a, fn: fn_03f1a as (...a: number[]) => void, params: [] },

  { at: 0x05cb0, fn: fn_05cb0 as (...a: number[]) => void, params: [{ from: 'reg', name: 'd0' }, { from: 'reg', name: 'd1' }, { from: 'stack', off: 4 }, { from: 'stack', off: 10 }] },

  { at: 0x05dea, fn: fn_05dea as (...a: number[]) => void, params: [] },

  { at: 0x05dfe, fn: fn_05dfe as (...a: number[]) => void, params: [] },

  { at: 0x05e00, fn: fn_05e00 as (...a: number[]) => void, params: [] },

  { at: 0x05e02, fn: fn_05e02 as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x05e08, fn: fn_05e08 as (...a: number[]) => void, params: [] },

  { at: 0x0663c, fn: fn_0663c as (...a: number[]) => void, params: [] },

  { at: 0x0a7e4, fn: fn_0a7e4 as (...a: number[]) => void, params: [] },

  { at: 0x0c4e8, fn: fn_0c4e8 as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x0db66, fn: fn_0db66 as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x0db6c, fn: fn_0db6c as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x0db72, fn: fn_0db72 as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x0db78, fn: fn_0db78 as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x0ee3a, fn: fn_0ee3a as (...a: number[]) => void, params: [] },

  { at: 0x0f2ee, fn: fn_0f2ee as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x0f2fa, fn: fn_0f2fa as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }] },

  { at: 0x0fc0e, fn: fn_0fc0e as (...a: number[]) => void, params: [] },

  { at: 0x1354c, fn: fn_1354c as (...a: number[]) => void, params: [] },

  { at: 0x193f2, fn: fn_193f2 as (...a: number[]) => void, params: [{ from: 'stack', off: 4 }, { from: 'stack', off: 11 }, { from: 'stack', off: 15 }] },

  { at: 0x1b11c, fn: fn_1b11c as (...a: number[]) => void, params: [{ from: 'reg', name: 'd0' }, { from: 'stack', off: 4 }] },

];
