// Generated by romlab/gen_ts.py - do not edit by hand.
// Routines 0x00118 - 0x00620 of the Rampart program overlay.

import { PendingInterrupt, type Machine } from './machine';
import { call } from './dispatch';

/** trampoline to 0x18df6 */
export function fn_00118(m: Machine, at = 0x00118): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00118: { m.next = 0x0011e; m.cycles += 20; pc = 0x18df6; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x19614 */
export function fn_0011e(m: Machine, at = 0x0011e): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0011e: { m.next = 0x00124; m.cycles += 20; pc = 0x19614; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x195b4 */
export function fn_00124(m: Machine, at = 0x00124): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00124: { m.next = 0x0012a; m.cycles += 20; pc = 0x195b4; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1946e */
export function fn_0012a(m: Machine, at = 0x0012a): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0012a: { m.next = 0x00130; m.cycles += 20; pc = 0x1946e; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18d88 */
export function fn_00130(m: Machine, at = 0x00130): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00130: { m.next = 0x00136; m.cycles += 20; pc = 0x18d88; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18dea */
export function fn_00136(m: Machine, at = 0x00136): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00136: { m.next = 0x0013c; m.cycles += 20; pc = 0x18dea; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18db6 */
export function fn_0013c(m: Machine, at = 0x0013c): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0013c: { m.next = 0x00142; m.cycles += 20; pc = 0x18db6; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18dfc */
export function fn_00142(m: Machine, at = 0x00142): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00142: { m.next = 0x00148; m.cycles += 20; pc = 0x18dfc; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18e00 */
export function fn_00148(m: Machine, at = 0x00148): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00148: { m.next = 0x0014e; m.cycles += 20; pc = 0x18e00; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18dc4 */
export function fn_0014e(m: Machine, at = 0x0014e): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0014e: { m.next = 0x00154; m.cycles += 20; pc = 0x18dc4; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18a5e */
export function fn_00154(m: Machine, at = 0x00154): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00154: { m.next = 0x0015a; m.cycles += 20; pc = 0x18a5e; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18764 */
export function fn_0015a(m: Machine, at = 0x0015a): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0015a: { m.next = 0x00160; m.cycles += 20; pc = 0x18764; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x19366 */
export function fn_00160(m: Machine, at = 0x00160): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00160: { m.next = 0x00166; m.cycles += 20; pc = 0x19366; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1939c */
export function fn_00166(m: Machine, at = 0x00166): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00166: { m.next = 0x0016c; m.cycles += 20; pc = 0x1939c; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x193da */
export function fn_0016c(m: Machine, at = 0x0016c): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0016c: { m.next = 0x00172; m.cycles += 20; pc = 0x193da; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x13e94 */
export function fn_00172(m: Machine, at = 0x00172): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00172: { m.next = 0x00178; m.cycles += 20; pc = 0x13e94; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14a36 */
export function fn_00178(m: Machine, at = 0x00178): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00178: { m.next = 0x0017e; m.cycles += 20; pc = 0x14a36; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14578 */
export function fn_0017e(m: Machine, at = 0x0017e): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0017e: { m.next = 0x00184; m.cycles += 20; pc = 0x14578; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14772 */
export function fn_00184(m: Machine, at = 0x00184): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00184: { m.next = 0x0018a; m.cycles += 20; pc = 0x14772; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1485c */
export function fn_0018a(m: Machine, at = 0x0018a): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0018a: { m.next = 0x00190; m.cycles += 20; pc = 0x1485c; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14b8a */
export function fn_00190(m: Machine, at = 0x00190): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00190: { m.next = 0x00196; m.cycles += 20; pc = 0x14b8a; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14c3c */
export function fn_00196(m: Machine, at = 0x00196): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00196: { m.next = 0x0019c; m.cycles += 20; pc = 0x14c3c; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14d48 */
export function fn_0019c(m: Machine, at = 0x0019c): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0019c: { m.next = 0x001a2; m.cycles += 20; pc = 0x14d48; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x15064 */
export function fn_001a2(m: Machine, at = 0x001a2): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001a2: { m.next = 0x001a8; m.cycles += 20; pc = 0x15064; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x155a0 */
export function fn_001a8(m: Machine, at = 0x001a8): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001a8: { m.next = 0x001ae; m.cycles += 20; pc = 0x155a0; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x15672 */
export function fn_001ae(m: Machine, at = 0x001ae): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001ae: { m.next = 0x001b4; m.cycles += 20; pc = 0x15672; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1568e */
export function fn_001b4(m: Machine, at = 0x001b4): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001b4: { m.next = 0x001ba; m.cycles += 20; pc = 0x1568e; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x156ac */
export function fn_001ba(m: Machine, at = 0x001ba): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001ba: { m.next = 0x001c0; m.cycles += 20; pc = 0x156ac; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x160ba */
export function fn_001c0(m: Machine, at = 0x001c0): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001c0: { m.next = 0x001c6; m.cycles += 20; pc = 0x160ba; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18e66 */
export function fn_001ca(m: Machine, at = 0x001ca): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001ca: { m.next = 0x001d0; m.cycles += 20; pc = 0x18e66; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x190f6 */
export function fn_001d0(m: Machine, at = 0x001d0): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001d0: { m.next = 0x001d6; m.cycles += 20; pc = 0x190f6; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x19032 */
export function fn_001d6(m: Machine, at = 0x001d6): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001d6: { m.next = 0x001dc; m.cycles += 20; pc = 0x19032; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x19010 */
export function fn_001dc(m: Machine, at = 0x001dc): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001dc: { m.next = 0x001e2; m.cycles += 20; pc = 0x19010; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18cce */
export function fn_001e2(m: Machine, at = 0x001e2): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001e2: { m.next = 0x001e8; m.cycles += 20; pc = 0x18cce; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x193c6 */
export function fn_001e8(m: Machine, at = 0x001e8): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001e8: { m.next = 0x001ee; m.cycles += 20; pc = 0x193c6; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1890c */
export function fn_001ee(m: Machine, at = 0x001ee): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001ee: { m.next = 0x001f4; m.cycles += 20; pc = 0x1890c; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x16bc8 */
export function fn_001f4(m: Machine, at = 0x001f4): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001f4: { m.next = 0x001fa; m.cycles += 20; pc = 0x16bc8; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x13f40 */
export function fn_001fa(m: Machine, at = 0x001fa): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x001fa: { m.next = 0x00200; m.cycles += 20; pc = 0x13f40; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x13f60 */
export function fn_00200(m: Machine, at = 0x00200): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00200: { m.next = 0x00206; m.cycles += 20; pc = 0x13f60; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x13f98 */
export function fn_00206(m: Machine, at = 0x00206): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00206: { m.next = 0x0020c; m.cycles += 20; pc = 0x13f98; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1418a */
export function fn_0020c(m: Machine, at = 0x0020c): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0020c: { m.next = 0x00212; m.cycles += 20; pc = 0x1418a; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14044 */
export function fn_00212(m: Machine, at = 0x00212): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00212: { m.next = 0x00218; m.cycles += 20; pc = 0x14044; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14104 */
export function fn_00218(m: Machine, at = 0x00218): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00218: { m.next = 0x0021e; m.cycles += 20; pc = 0x14104; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14138 */
export function fn_0021e(m: Machine, at = 0x0021e): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0021e: { m.next = 0x00224; m.cycles += 20; pc = 0x14138; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x141c4 */
export function fn_00224(m: Machine, at = 0x00224): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00224: { m.next = 0x0022a; m.cycles += 20; pc = 0x141c4; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x141d4 */
export function fn_0022a(m: Machine, at = 0x0022a): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0022a: { m.next = 0x00230; m.cycles += 20; pc = 0x141d4; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x14230 */
export function fn_00230(m: Machine, at = 0x00230): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00230: { m.next = 0x00236; m.cycles += 20; pc = 0x14230; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1a0cc */
export function fn_00236(m: Machine, at = 0x00236): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00236: { m.next = 0x0023c; m.cycles += 20; pc = 0x1a0cc; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x19f3e */
export function fn_0023c(m: Machine, at = 0x0023c): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0023c: { m.next = 0x00242; m.cycles += 20; pc = 0x19f3e; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1684c */
export function fn_00242(m: Machine, at = 0x00242): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00242: { m.next = 0x00248; m.cycles += 20; pc = 0x1684c; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18b76 */
export function fn_00248(m: Machine, at = 0x00248): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00248: { m.next = 0x0024e; m.cycles += 20; pc = 0x18b76; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18b26 */
export function fn_0024e(m: Machine, at = 0x0024e): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0024e: { m.next = 0x00254; m.cycles += 20; pc = 0x18b26; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18b5c */
export function fn_00254(m: Machine, at = 0x00254): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00254: { m.next = 0x0025a; m.cycles += 20; pc = 0x18b5c; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x190da */
export function fn_0025a(m: Machine, at = 0x0025a): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0025a: { m.next = 0x00260; m.cycles += 20; pc = 0x190da; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x1908a */
export function fn_00260(m: Machine, at = 0x00260): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00260: { m.next = 0x00266; m.cycles += 20; pc = 0x1908a; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x190c0 */
export function fn_00266(m: Machine, at = 0x00266): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00266: { m.next = 0x0026c; m.cycles += 20; pc = 0x190c0; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x183f2 */
export function fn_0026c(m: Machine, at = 0x0026c): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0026c: { m.next = 0x00272; m.cycles += 20; pc = 0x183f2; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x15830 */
export function fn_00272(m: Machine, at = 0x00272): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00272: { m.next = 0x00278; m.cycles += 20; pc = 0x15830; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x15858 */
export function fn_00278(m: Machine, at = 0x00278): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00278: { m.next = 0x0027e; m.cycles += 20; pc = 0x15858; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x19c2e */
export function fn_0027e(m: Machine, at = 0x0027e): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0027e: { m.next = 0x00284; m.cycles += 20; pc = 0x19c2e; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x18afe */
export function fn_00286(m: Machine, at = 0x00286): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00286: { m.next = 0x0028c; m.cycles += 20; pc = 0x18afe; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x19054 */
export function fn_0028c(m: Machine, at = 0x0028c): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0028c: { m.next = 0x00292; m.cycles += 20; pc = 0x19054; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x13cda */
export function fn_00292(m: Machine, at = 0x00292): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00292: { m.next = 0x00298; m.cycles += 20; pc = 0x13cda; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x003ea */
export function fn_00300(m: Machine, at = 0x00300): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00300: { m.next = 0x00306; m.cycles += 20; pc = 0x003ea; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x00580 */
export function fn_00306(m: Machine, at = 0x00306): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00306: { m.next = 0x0030c; m.cycles += 20; pc = 0x00580; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** routine */
export function fn_003e8(m: Machine, at = 0x003e8): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x003e8: { m.next = 0x003ea; m.cycles += 34; { m.trap(0); m.storePre('a7', 4, 0x003ea, 32); m.storePre('a7', 2, m.getSR(), 16); pc = m.load(0x80, 32); } break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** computed-jump entry at 0x003ea */
export function fn_003ea(m: Machine, at = 0x003ea): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x003ea: { m.next = 0x003f0; m.cycles += 28; m.storePre('a7', 4, 0x003f0, 32); call(0x00618, m); pc = 0x003f0; } break;
      case 0x003f0: { m.next = 0x003f6; m.cycles += 18; m.a0 = m.wr(m.a0, 0x3e3f00, 32); pc = 0x003f6; } break;
      case 0x003f6: { m.next = 0x003fa; m.cycles += 8; { const _s = 9; m.storePost('a0', 2, _s, 16); m.logicFlags(_s, 16); } pc = 0x003fa; } break;
      case 0x003fa: { m.next = 0x003fe; m.cycles += 8; { const _s = 13; m.storePost('a0', 2, _s, 16); m.logicFlags(_s, 16); } pc = 0x003fe; } break;
      case 0x003fe: { m.next = 0x00402; m.cycles += 8; { const _s = 10; m.storePost('a0', 2, _s, 16); m.logicFlags(_s, 16); } pc = 0x00402; } break;
      case 0x00402: { m.next = 0x00406; m.cycles += 8; { const _s = 14; m.storePost('a0', 2, _s, 16); m.logicFlags(_s, 16); } pc = 0x00406; } break;
      case 0x00406: { m.next = 0x0040e; m.cycles += 16; { const _s = 23445; m.store(0x3e3f08, _s, 16); m.logicFlags(_s, 16); } pc = 0x0040e; } break;
      case 0x0040e: { m.next = 0x00416; m.cycles += 16; { const _s = 4118; m.store(0x3e3f0a, _s, 16); m.logicFlags(_s, 16); } pc = 0x00416; } break;
      case 0x00416: { m.next = 0x0041e; m.cycles += 16; { const _s = 45191; m.store(0x3e3f0c, _s, 16); m.logicFlags(_s, 16); } pc = 0x0041e; } break;
      case 0x0041e: { m.next = 0x00424; m.cycles += 16; m.store(0x3e0802, 0, 16); m.logicFlags(0, 16); pc = 0x00424; } break;
      case 0x00424: { m.next = 0x0042a; m.cycles += 16; m.store(0x3e0800, 0, 16); m.logicFlags(0, 16); pc = 0x0042a; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** trampoline to 0x09188 */
export function fn_0042a(m: Machine, at = 0x0042a): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0042a: { m.next = 0x00430; m.cycles += 20; pc = 0x09188; break; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** helper for accessor for the state block at 0x3E1946 */
export function fn_00430(m: Machine, at = 0x00430): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00430: { m.next = 0x00434; m.cycles += 60; m.storePre('a7', 4, m.a1, 32); m.storePre('a7', 4, m.a0, 32); m.storePre('a7', 4, m.d3, 32); m.storePre('a7', 4, m.d2, 32); pc = 0x00434; } break;
      case 0x00434: { m.next = 0x0043a; m.cycles += 6; { const _s = 1431655765; m.d0 = m.wr(m.d0, _s, 32); m.logicFlags(_s, 32); } pc = 0x0043a; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** dispatcher gate check */
export function fn_00438(m: Machine, at = 0x00438): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00438: { m.next = 0x0043a; m.cycles += 8; { const _a = 2; const _ea = (m.a5) >>> 0; const _b = m.load(_ea, 16); m.store(_ea, m.subFlags(_b, _a, 16), 16); } pc = 0x0043a; } break;
      case 0x0043a: { m.next = 0x00440; m.cycles += 6; { const _s = 2863311530; m.d1 = m.wr(m.d1, _s, 32); m.logicFlags(_s, 32); } pc = 0x00440; } break;
      case 0x00440: { m.next = 0x00442; m.cycles += 4; m.d2 = m.wr(m.d2, (4294967295 >>> 0), 32); m.logicFlags(-1, 32); pc = 0x00442; } break;
      case 0x00442: { m.next = 0x00444; m.cycles += 4; m.d3 = m.wr(m.d3, (0 >>> 0), 32); m.logicFlags(0, 32); pc = 0x00444; } break;
      case 0x00444: { m.next = 0x0044a; m.cycles += 16; m.logicFlags(m.load(0x3e0802, 16), 16); pc = 0x0044a; } break;
      case 0x0044a: { m.next = 0x0044e; m.cycles += 10; if (m.cond('ne')) { pc = 0x00482; } else { pc = 0x0044e; } } break;
      case 0x0044e: { m.next = 0x00452; m.cycles += 44; m.storePre('a7', 4, m.d3, 32); m.storePre('a7', 4, m.d2, 32); m.storePre('a7', 4, m.d1, 32); m.storePre('a7', 4, m.d0, 32); pc = 0x00452; } break;
      case 0x00452: { m.next = 0x00454; m.cycles += 10; { const _a = m.load(m.a7, 32); const _b = m.rd(m.d0, 32); m.subFlags(_b, _a, 32, false); } pc = 0x00454; } break;
      case 0x00454: { m.next = 0x00456; m.cycles += 10; if (m.cond('ne')) { pc = 0x00478; } else { pc = 0x00456; } } break;
      case 0x00456: { m.next = 0x0045a; m.cycles += 14; { const _a = m.load(m.a7 + 4, 32); const _b = m.rd(m.d1, 32); m.subFlags(_b, _a, 32, false); } pc = 0x0045a; } break;
      case 0x0045a: { m.next = 0x0045c; m.cycles += 10; if (m.cond('ne')) { pc = 0x00478; } else { pc = 0x0045c; } } break;
      case 0x0045c: { m.next = 0x00460; m.cycles += 14; { const _a = m.load(m.a7 + 8, 32); const _b = m.rd(m.d2, 32); m.subFlags(_b, _a, 32, false); } pc = 0x00460; } break;
      case 0x00460: { m.next = 0x00462; m.cycles += 10; if (m.cond('ne')) { pc = 0x00478; } else { pc = 0x00462; } } break;
      case 0x00462: { m.next = 0x00466; m.cycles += 14; { const _a = m.load(m.a7 + 12, 32); const _b = m.rd(m.d3, 32); m.subFlags(_b, _a, 32, false); } pc = 0x00466; } break;
      case 0x00466: { m.next = 0x00468; m.cycles += 10; if (m.cond('ne')) { pc = 0x00478; } else { pc = 0x00468; } } break;
      case 0x00468: { m.next = 0x0046c; m.cycles += 34; m.d0 = m.loadPost('a7', 4, 32); m.d1 = m.loadPost('a7', 4, 32); m.d2 = m.loadPost('a7', 4, 32); m.d3 = m.loadPost('a7', 4, 32); pc = 0x0046c; } break;
      case 0x0046c: { m.next = 0x0046e; m.cycles += 12; { const _s = m.rd(m.d0, 32); m.storePre('a7', 4, _s, 32); m.logicFlags(_s, 32); } pc = 0x0046e; } break;
      case 0x0046e: { m.next = 0x00470; m.cycles += 6; { const _s = m.rd(m.d1, 32); m.d0 = m.wr(m.d0, _s, 32); m.logicFlags(_s, 32); } pc = 0x00470; } break;
      case 0x00470: { m.next = 0x00472; m.cycles += 6; { const _s = m.rd(m.d2, 32); m.d1 = m.wr(m.d1, _s, 32); m.logicFlags(_s, 32); } pc = 0x00472; } break;
      case 0x00472: { m.next = 0x00474; m.cycles += 6; { const _s = m.rd(m.d3, 32); m.d2 = m.wr(m.d2, _s, 32); m.logicFlags(_s, 32); } pc = 0x00474; } break;
      case 0x00474: { m.next = 0x00476; m.cycles += 10; { const _s = m.loadPost('a7', 4, 32); m.d3 = m.wr(m.d3, _s, 32); m.logicFlags(_s, 32); } pc = 0x00476; } break;
      case 0x00476: { m.next = 0x00478; m.cycles += 10; pc = 0x00444; break; } break;
      case 0x00478: { m.next = 0x0047e; m.cycles += 26; m.storePre('a7', 4, 0x3ab, 32); pc = 0x0047e; } break;
      case 0x0047e: { m.next = 0x00482; m.cycles += 30; m.storePre('a7', 4, 0x00482, 32); call(0x003e8, m); pc = 0x00482; } break;
      case 0x00482: { m.next = 0x00488; m.cycles += 16; { const _a = 1; const _ea = (0x3e0802) >>> 0; const _b = m.load(_ea, 16); m.store(_ea, m.subFlags(_b, _a, 16), 16); } pc = 0x00488; } break;
      case 0x00488: { m.next = 0x0048e; m.cycles += 16; { const _s = m.load(0x3e0802, 16); m.d0 = m.wr(m.d0, _s, 16); m.logicFlags(_s, 16); } pc = 0x0048e; } break;
      case 0x0048e: { m.next = 0x00492; m.cycles += 8; { const _a = 4; const _b = m.rd(m.d0, 16); m.subFlags(_b, _a, 16, false); } pc = 0x00492; } break;
      case 0x00492: { m.next = 0x00494; m.cycles += 10; if (m.cond('lt')) { pc = 0x0049c; } else { pc = 0x00494; } } break;
      case 0x00494: { m.next = 0x0049c; m.cycles += 16; { const _s = 4; m.store(0x3e0802, _s, 16); m.logicFlags(_s, 16); } pc = 0x0049c; } break;
      case 0x0049c: { m.next = 0x004a2; m.cycles += 16; m.logicFlags(m.load(0x3e1948, 16), 16); pc = 0x004a2; } break;
      case 0x004a2: { m.next = 0x004a4; m.cycles += 10; if (m.cond('eq')) { pc = 0x004fa; } else { pc = 0x004a4; } } break;
      case 0x004a4: { m.next = 0x004aa; m.cycles += 18; m.a0 = m.wr(m.a0, 0x6c0007, 32); pc = 0x004aa; } break;
      case 0x004aa: { m.next = 0x004b0; m.cycles += 18; m.a1 = m.wr(m.a1, 0x3e0806, 32); pc = 0x004b0; } break;
      case 0x004b0: { m.next = 0x004b4; m.cycles += 30; m.storePre('a7', 4, 0x004b4, 32); call(0x00534, m); pc = 0x004b4; } break;
      case 0x004b4: { m.next = 0x004ba; m.cycles += 18; m.a0 = m.wr(m.a0, 0x6c0005, 32); pc = 0x004ba; } break;
      case 0x004ba: { m.next = 0x004c0; m.cycles += 18; m.a1 = m.wr(m.a1, 0x3e080e, 32); pc = 0x004c0; } break;
      case 0x004c0: { m.next = 0x004c2; m.cycles += 30; m.storePre('a7', 4, 0x004c2, 32); call(0x00534, m); pc = 0x004c2; } break;
      case 0x004c2: { m.next = 0x004c8; m.cycles += 18; m.a0 = m.wr(m.a0, 0x6c0003, 32); pc = 0x004c8; } break;
      case 0x004c8: { m.next = 0x004ce; m.cycles += 18; m.a1 = m.wr(m.a1, 0x3e0816, 32); pc = 0x004ce; } break;
      case 0x004ce: { m.next = 0x004d0; m.cycles += 30; m.storePre('a7', 4, 0x004d0, 32); call(0x00534, m); pc = 0x004d0; } break;
      case 0x004d0: { m.next = 0x004d6; m.cycles += 18; m.a0 = m.wr(m.a0, 0x6c0001, 32); pc = 0x004d6; } break;
      case 0x004d6: { m.next = 0x004dc; m.cycles += 18; m.a1 = m.wr(m.a1, 0x3e081e, 32); pc = 0x004dc; } break;
      case 0x004dc: { m.next = 0x004de; m.cycles += 30; m.storePre('a7', 4, 0x004de, 32); call(0x00534, m); pc = 0x004de; } break;
      case 0x004de: { m.next = 0x004e4; m.cycles += 18; m.a0 = m.wr(m.a0, 0x6c0002, 32); pc = 0x004e4; } break;
      case 0x004e4: { m.next = 0x004ea; m.cycles += 18; m.a1 = m.wr(m.a1, 0x3e0826, 32); pc = 0x004ea; } break;
      case 0x004ea: { m.next = 0x004ec; m.cycles += 30; m.storePre('a7', 4, 0x004ec, 32); call(0x00534, m); pc = 0x004ec; } break;
      case 0x004ec: { m.next = 0x004f2; m.cycles += 18; m.a0 = m.wr(m.a0, 0x6c0000, 32); pc = 0x004f2; } break;
      case 0x004f2: { m.next = 0x004f8; m.cycles += 18; m.a1 = m.wr(m.a1, 0x3e082e, 32); pc = 0x004f8; } break;
      case 0x004f8: { m.next = 0x004fa; m.cycles += 30; m.storePre('a7', 4, 0x004fa, 32); call(0x00534, m); pc = 0x004fa; } break;
      case 0x004fa: { m.next = 0x00500; m.cycles += 28; m.storePre('a7', 4, 0x00500, 32); call(0x09080, m); pc = 0x00500; } break;
      case 0x00500: { m.next = 0x00506; m.cycles += 16; { const _a = 1; const _ea = (0x3e1cf2) >>> 0; const _b = m.load(_ea, 8); m.store(_ea, m.subFlags(_b, _a, 8), 8); } pc = 0x00506; } break;
      case 0x00506: { m.next = 0x0050c; m.cycles += 16; { const _a = 1; const _ea = (0x3e0800) >>> 0; const _b = m.load(_ea, 16); m.store(_ea, m.addFlags(_b, _a, 16), 16); } pc = 0x0050c; } break;
      case 0x0050c: { m.next = 0x00510; m.cycles += 50; m.d2 = m.loadPost('a7', 4, 32); m.d3 = m.loadPost('a7', 4, 32); m.a0 = m.loadPost('a7', 4, 32); m.a1 = m.loadPost('a7', 4, 32); pc = 0x00510; } break;
      case 0x00510: { m.next = 0x00512; m.cycles += 16; m.a7 = (m.a7 + 4) >>> 0; return; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** small leaf utility */
export function fn_00512(m: Machine, at = 0x00512): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00512: { m.next = 0x0051a; m.cycles += 16; { const _s = 0; m.store(0x3e0802, _s, 16); m.logicFlags(_s, 16); } pc = 0x0051a; } break;
      case 0x0051a: { m.next = 0x00520; m.cycles += 16; m.logicFlags(m.load(0x3e0802, 16), 16); pc = 0x00520; } break;
      case 0x00520: { m.next = 0x00522; m.cycles += 10; if (m.cond('eq')) { pc = 0x0051a; } else { pc = 0x00522; } } break;
      case 0x00522: { m.next = 0x00528; m.cycles += 16; { const _a = 1; const _ea = (0x3e0802) >>> 0; const _b = m.load(_ea, 16); m.store(_ea, m.subFlags(_b, _a, 16), 16); } pc = 0x00528; } break;
      case 0x00528: { m.next = 0x0052a; m.cycles += 16; m.a7 = (m.a7 + 4) >>> 0; return; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** small leaf utility */
export function fn_0052a(m: Machine, at = 0x0052a): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x0052a: { m.next = 0x00532; m.cycles += 16; { const _s = 0; m.store(0x3e0802, _s, 16); m.logicFlags(_s, 16); } pc = 0x00532; } break;
      case 0x00532: { m.next = 0x00534; m.cycles += 16; m.a7 = (m.a7 + 4) >>> 0; return; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** negate and store */
export function fn_00534(m: Machine, at = 0x00534): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00534: { m.next = 0x00538; m.cycles += 16; { const _s = m.load(m.a1, 16); m.store(m.a1 + 2, _s, 16); m.logicFlags(_s, 16); } pc = 0x00538; } break;
      case 0x00538: { m.next = 0x0053a; m.cycles += 8; { const _s = m.load(m.a0, 8); m.d0 = m.wr(m.d0, _s, 8); m.logicFlags(_s, 8); } pc = 0x0053a; } break;
      case 0x0053a: { m.next = 0x0053c; m.cycles += 4; {  const _v = m.rd(m.d0, 8); m.d0 = m.wr(m.d0, m.subFlags(0, _v, 8), 8); } pc = 0x0053c; } break;
      case 0x0053c: { m.next = 0x00540; m.cycles += 12; { const _s = m.load(m.a1 + 4, 8); m.d3 = m.wr(m.d3, _s, 8); m.logicFlags(_s, 8); } pc = 0x00540; } break;
      case 0x00540: { m.next = 0x00544; m.cycles += 12; { const _s = m.rd(m.d0, 8); m.store(m.a1 + 0, _s, 8); m.logicFlags(_s, 8); } pc = 0x00544; } break;
      case 0x00544: { m.next = 0x00548; m.cycles += 12; { const _a = m.load(m.a1 + 2, 8);  const _b = m.rd(m.d0, 8); m.d0 = m.wr(m.d0, m.subFlags(_b, _a, 8), 8); } pc = 0x00548; } break;
      case 0x00548: { m.next = 0x0054a; m.cycles += 10; if (m.cond('mi')) { pc = 0x00552; } else { pc = 0x0054a; } } break;
      case 0x0054a: { m.next = 0x0054c; m.cycles += 10; if (m.cond('ne')) { pc = 0x00560; } else { pc = 0x0054c; } } break;
      case 0x0054c: { m.next = 0x0054e; m.cycles += 4; m.logicFlags(m.rd(m.d3, 8), 8); pc = 0x0054e; } break;
      case 0x0054e: { m.next = 0x00550; m.cycles += 10; if (m.cond('eq')) { pc = 0x0056c; } else { pc = 0x00550; } } break;
      case 0x00550: { m.next = 0x00552; m.cycles += 10; pc = 0x00572; break; } break;
      case 0x00552: { m.next = 0x00554; m.cycles += 4; m.logicFlags(m.rd(m.d3, 8), 8); pc = 0x00554; } break;
      case 0x00554: { m.next = 0x00556; m.cycles += 10; if (m.cond('ge')) { pc = 0x00572; } else { pc = 0x00556; } } break;
      case 0x00556: { m.next = 0x0055a; m.cycles += 8; { const _a = 224; const _b = m.rd(m.d0, 8); m.subFlags(_b, _a, 8, false); } pc = 0x0055a; } break;
      case 0x0055a: { m.next = 0x0055c; m.cycles += 10; if (m.cond('lt')) { pc = 0x00578; } else { pc = 0x0055c; } } break;
      case 0x0055c: { m.next = 0x0055e; m.cycles += 6; { const _c = (1) & 63;  const _v = m.sx(m.rd(m.d0, 8), 8); const _r = (_c >= 8 ? (_v >> 7) : (_v >> _c)); m.d0 = m.wr(m.d0, _r, 8); m.shiftFlags(_r, _v, _c, 8, false, true); } pc = 0x0055e; } break;
      case 0x0055e: { m.next = 0x00560; m.cycles += 10; pc = 0x0056c; break; } break;
      case 0x00560: { m.next = 0x00562; m.cycles += 4; m.logicFlags(m.rd(m.d3, 8), 8); pc = 0x00562; } break;
      case 0x00562: { m.next = 0x00564; m.cycles += 10; if (m.cond('le')) { pc = 0x00572; } else { pc = 0x00564; } } break;
      case 0x00564: { m.next = 0x00568; m.cycles += 8; { const _a = 32; const _b = m.rd(m.d0, 8); m.subFlags(_b, _a, 8, false); } pc = 0x00568; } break;
      case 0x00568: { m.next = 0x0056a; m.cycles += 10; if (m.cond('gt')) { pc = 0x00578; } else { pc = 0x0056a; } } break;
      case 0x0056a: { m.next = 0x0056c; m.cycles += 6; { const _c = (1) & 63;  const _v = m.sx(m.rd(m.d0, 8), 8); const _r = (_c >= 8 ? (_v >> 7) : (_v >> _c)); m.d0 = m.wr(m.d0, _r, 8); m.shiftFlags(_r, _v, _c, 8, false, true); } pc = 0x0056c; } break;
      case 0x0056c: { m.next = 0x00570; m.cycles += 12; { const _s = m.rd(m.d0, 8); m.store(m.a1 + 4, _s, 8); m.logicFlags(_s, 8); } pc = 0x00570; } break;
      case 0x00570: { m.next = 0x00572; m.cycles += 10; pc = 0x00578; break; } break;
      case 0x00572: { m.next = 0x00576; m.cycles += 12; { const _s = m.rd(m.d0, 8); m.store(m.a1 + 4, _s, 8); m.logicFlags(_s, 8); } pc = 0x00576; } break;
      case 0x00576: { m.next = 0x00578; m.cycles += 6; m.d0 = m.wr(m.d0, 0, 32); m.logicFlags(0, 32); pc = 0x00578; } break;
      case 0x00578: { m.next = 0x0057a; m.cycles += 4; { const _r = m.sx(m.rd(m.d0, 16), 8); m.d0 = m.wr(m.d0, _r, 16); m.logicFlags(_r, 16); } pc = 0x0057a; } break;
      case 0x0057a: { m.next = 0x0057e; m.cycles += 12; { const _a = m.rd(m.d0, 16); const _ea = ((m.a1 + 6)) >>> 0; const _b = m.load(_ea, 16); m.store(_ea, m.addFlags(_b, _a, 16), 16); } pc = 0x0057e; } break;
      case 0x0057e: { m.next = 0x00580; m.cycles += 16; m.a7 = (m.a7 + 4) >>> 0; return; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** vblank gate tick */
export function fn_00580(m: Machine, at = 0x00580): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00580: { m.next = 0x00586; m.cycles += 16; m.store(0x7effff, 0, 8); m.logicFlags(0, 8); pc = 0x00586; } break;
      case 0x00586: { m.next = 0x0058c; m.cycles += 16; { const _a = 1; const _ea = (0x3e0802) >>> 0; const _b = m.load(_ea, 16); m.store(_ea, m.addFlags(_b, _a, 16), 16); } pc = 0x0058c; } break;
      case 0x0058c: { m.next = 0x00594; m.cycles += 20; { const _a = 120; const _b = m.load(0x3e0802, 16); m.subFlags(_b, _a, 16, false); } pc = 0x00594; } break;
      case 0x00594: { m.next = 0x00596; m.cycles += 10; if (m.cond('gt')) { pc = 0x00594; } else { pc = 0x00596; } } break;
      case 0x00596: { m.next = 0x0059c; m.cycles += 28; m.storePre('a7', 4, 0x0059c, 32); call(0x00618, m); pc = 0x0059c; } break;
      case 0x0059c: { m.next = 0x005a2; m.cycles += 28; m.storePre('a7', 4, 0x005a2, 32); call(0x125da, m); pc = 0x005a2; } break;
      case 0x005a2: { m.next = 0x005a8; m.cycles += 28; m.storePre('a7', 4, 0x005a8, 32); call(0x01512, m); pc = 0x005a8; } break;
      case 0x005a8: { m.next = 0x005ae; m.cycles += 28; m.storePre('a7', 4, 0x005ae, 32); call(0x053f8, m); pc = 0x005ae; } break;
      case 0x005ae: { m.next = 0x005b0; m.cycles += 16; m.a7 = (m.a7 + 4) >>> 0; return; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** helper for player state access */
export function fn_005b4(m: Machine, at = 0x005b4): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x005b4: { m.next = 0x005b6; m.cycles += 12; { const _s = m.rd(m.d2, 32); m.storePre('a7', 4, _s, 32); m.logicFlags(_s, 32); } pc = 0x005b6; } break;
      case 0x005b6: { m.next = 0x005bc; m.cycles += 18; m.a1 = m.wr(m.a1, 0x3e0836, 32); pc = 0x005bc; } break;
      case 0x005bc: { m.next = 0x005c0; m.cycles += 12; { const _s = m.load(m.a7 + 10, 16); m.d1 = m.wr(m.d1, _s, 16); m.logicFlags(_s, 16); } pc = 0x005c0; } break;
      case 0x005c0: { m.next = 0x005c2; m.cycles += 10; if (m.cond('ne')) { pc = 0x005ca; } else { pc = 0x005c2; } } break;
      case 0x005c2: { m.next = 0x005c8; m.cycles += 16; { const _s = m.load(0x640002, 8); m.d0 = m.wr(m.d0, _s, 8); m.logicFlags(_s, 8); } pc = 0x005c8; } break;
      case 0x005c8: { m.next = 0x005ca; m.cycles += 10; pc = 0x005de; break; } break;
      case 0x005ca: { m.next = 0x005ce; m.cycles += 8; { const _a = 1; const _b = m.rd(m.d1, 16); m.subFlags(_b, _a, 16, false); } pc = 0x005ce; } break;
      case 0x005ce: { m.next = 0x005d0; m.cycles += 10; if (m.cond('ne')) { pc = 0x005d8; } else { pc = 0x005d0; } } break;
      case 0x005d0: { m.next = 0x005d6; m.cycles += 16; { const _s = m.load(0x640000, 8); m.d0 = m.wr(m.d0, _s, 8); m.logicFlags(_s, 8); } pc = 0x005d6; } break;
      case 0x005d6: { m.next = 0x005d8; m.cycles += 10; pc = 0x005de; break; } break;
      case 0x005d8: { m.next = 0x005de; m.cycles += 16; { const _s = m.load(0x640001, 8); m.d0 = m.wr(m.d0, _s, 8); m.logicFlags(_s, 8); } pc = 0x005de; } break;
      case 0x005de: { m.next = 0x005e0; m.cycles += 8; { const _a = m.sx(m.rd(m.d1, 16), 16); m.a1 = m.wr(m.a1, (m.rd(m.a1, 32) + _a), 32); } pc = 0x005e0; } break;
      case 0x005e0: { m.next = 0x005e4; m.cycles += 14; { const _s = m.load(0 + 1456 + m.sx(m.d1, 16), 8); m.d1 = m.wr(m.d1, _s, 8); m.logicFlags(_s, 8); } pc = 0x005e4; } break;
      case 0x005e4: { m.next = 0x005e6; m.cycles += 4; { const _a = m.rd(m.d1, 8);  const _b = m.rd(m.d0, 8); const _r = (_b ^ _a); m.d0 = m.wr(m.d0, _r, 8); m.logicFlags(_r, 8); } pc = 0x005e6; } break;
      case 0x005e6: { m.next = 0x005e8; m.cycles += 8; { const _s = m.load(m.a1, 8); m.d2 = m.wr(m.d2, _s, 8); m.logicFlags(_s, 8); } pc = 0x005e8; } break;
      case 0x005e8: { m.next = 0x005ea; m.cycles += 4; { const _s = m.rd(m.d0, 8); m.d1 = m.wr(m.d1, _s, 8); m.logicFlags(_s, 8); } pc = 0x005ea; } break;
      case 0x005ea: { m.next = 0x005ee; m.cycles += 12; { const _a = m.load(m.a1 + 6, 8);  const _b = m.rd(m.d0, 8); const _r = (_b & _a); m.d0 = m.wr(m.d0, _r, 8); m.logicFlags(_r, 8); } pc = 0x005ee; } break;
      case 0x005ee: { m.next = 0x005f0; m.cycles += 4; { const _a = m.rd(m.d0, 8);  const _b = m.rd(m.d2, 8); const _r = (_b | _a); m.d2 = m.wr(m.d2, _r, 8); m.logicFlags(_r, 8); } pc = 0x005f0; } break;
      case 0x005f0: { m.next = 0x005f2; m.cycles += 4; { const _s = m.rd(m.d1, 8); m.d0 = m.wr(m.d0, _s, 8); m.logicFlags(_s, 8); } pc = 0x005f2; } break;
      case 0x005f2: { m.next = 0x005f6; m.cycles += 12; { const _a = m.load(m.a1 + 6, 8);  const _b = m.rd(m.d0, 8); const _r = (_b | _a); m.d0 = m.wr(m.d0, _r, 8); m.logicFlags(_r, 8); } pc = 0x005f6; } break;
      case 0x005f6: { m.next = 0x005f8; m.cycles += 4; { const _a = m.rd(m.d0, 8);  const _b = m.rd(m.d2, 8); const _r = (_b & _a); m.d2 = m.wr(m.d2, _r, 8); m.logicFlags(_r, 8); } pc = 0x005f8; } break;
      case 0x005f8: { m.next = 0x005fa; m.cycles += 8; { const _a = m.rd(m.d0, 8); const _ea = (m.a1) >>> 0; const _b = m.load(_ea, 8); const _r = (_b & _a); m.store(_ea, _r, 8); m.logicFlags(_r, 8); } pc = 0x005fa; } break;
      case 0x005fa: { m.next = 0x005fe; m.cycles += 12; { const _s = m.rd(m.d1, 8); m.store(m.a1 + 6, _s, 8); m.logicFlags(_s, 8); } pc = 0x005fe; } break;
      case 0x005fe: { m.next = 0x00600; m.cycles += 10; { const _s = m.rd(m.d2, 8); m.storePre('a7', 2, _s, 8); m.logicFlags(_s, 8); } pc = 0x00600; } break;
      case 0x00600: { m.next = 0x00602; m.cycles += 8; { const _s = m.loadPost('a7', 2, 16); m.d0 = m.wr(m.d0, _s, 16); m.logicFlags(_s, 16); } pc = 0x00602; } break;
      case 0x00602: { m.next = 0x00604; m.cycles += 8; { const _s = m.load(m.a1, 8); m.d0 = m.wr(m.d0, _s, 8); m.logicFlags(_s, 8); } pc = 0x00604; } break;
      case 0x00604: { m.next = 0x00606; m.cycles += 4; { const _a = m.rd(m.d2, 8);  const _b = m.rd(m.d0, 8); const _r = (_b ^ _a); m.d0 = m.wr(m.d0, _r, 8); m.logicFlags(_r, 8); } pc = 0x00606; } break;
      case 0x00606: { m.next = 0x0060a; m.cycles += 12; { const _s = m.load(m.a7 + 15, 8); m.d1 = m.wr(m.d1, _s, 8); m.logicFlags(_s, 8); } pc = 0x0060a; } break;
      case 0x0060a: { m.next = 0x0060c; m.cycles += 4; { const _a = m.rd(m.d1, 8);  const _b = m.rd(m.d0, 8); const _r = (_b & _a); m.d0 = m.wr(m.d0, _r, 8); m.logicFlags(_r, 8); } pc = 0x0060c; } break;
      case 0x0060c: { m.next = 0x0060e; m.cycles += 8; { const _a = m.rd(m.d0, 8); const _ea = (m.a1) >>> 0; const _b = m.load(_ea, 8); const _r = (_b | _a); m.store(_ea, _r, 8); m.logicFlags(_r, 8); } pc = 0x0060e; } break;
      case 0x0060e: { m.next = 0x00610; m.cycles += 4; {  const _r = (~m.rd(m.d1, 8)); m.d1 = m.wr(m.d1, _r, 8); m.logicFlags(_r, 8); } pc = 0x00610; } break;
      case 0x00610: { m.next = 0x00612; m.cycles += 4; { const _a = m.rd(m.d1, 8);  const _b = m.rd(m.d2, 8); const _r = (_b & _a); m.d2 = m.wr(m.d2, _r, 8); m.logicFlags(_r, 8); } pc = 0x00612; } break;
      case 0x00612: { m.next = 0x00614; m.cycles += 4; { const _a = m.rd(m.d2, 8);  const _b = m.rd(m.d0, 8); const _r = (_b | _a); m.d0 = m.wr(m.d0, _r, 8); m.logicFlags(_r, 8); } pc = 0x00614; } break;
      case 0x00614: { m.next = 0x00616; m.cycles += 10; { const _s = m.loadPost('a7', 4, 32); m.d2 = m.wr(m.d2, _s, 32); m.logicFlags(_s, 32); } pc = 0x00616; } break;
      case 0x00616: { m.next = 0x00618; m.cycles += 16; m.a7 = (m.a7 + 4) >>> 0; return; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}

/** small leaf utility */
export function fn_00618(m: Machine, at = 0x00618): void {
  let pc = at;
  for (;;) {
    try {
    m.tick(pc);
    if (m.stopped) return;
    switch (pc) {
      case 0x00618: { m.next = 0x0061e; m.cycles += 16; m.store(0x72ffff, 0, 8); m.logicFlags(0, 8); pc = 0x0061e; } break;
      case 0x0061e: { m.next = 0x00620; m.cycles += 16; m.a7 = (m.a7 + 4) >>> 0; return; } break;
      default: m.jump = pc; return;
    }
    } catch (e) {
      if (!(e instanceof PendingInterrupt)) throw e;
      if (e.afterInstruction) pc = m.next;
      call(m.interruptFrame(e.level), m);
    }
  }
}
