// Generated by romlab/gen_ts.py - do not edit by hand.
// Routines 0x00118 - 0x00266 of the Rampart program overlay.

import type { Machine } from './machine';
import { call } from './dispatch';

/** trampoline to 0x18df6 */
export function fn_00118(m: Machine, at = 0x00118): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00118: { pc = 0x18df6; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x19614 */
export function fn_0011e(m: Machine, at = 0x0011e): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0011e: { pc = 0x19614; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x195b4 */
export function fn_00124(m: Machine, at = 0x00124): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00124: { pc = 0x195b4; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1946e */
export function fn_0012a(m: Machine, at = 0x0012a): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0012a: { pc = 0x1946e; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18d88 */
export function fn_00130(m: Machine, at = 0x00130): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00130: { pc = 0x18d88; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18dea */
export function fn_00136(m: Machine, at = 0x00136): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00136: { pc = 0x18dea; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18db6 */
export function fn_0013c(m: Machine, at = 0x0013c): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0013c: { pc = 0x18db6; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18dfc */
export function fn_00142(m: Machine, at = 0x00142): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00142: { pc = 0x18dfc; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18e00 */
export function fn_00148(m: Machine, at = 0x00148): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00148: { pc = 0x18e00; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18dc4 */
export function fn_0014e(m: Machine, at = 0x0014e): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0014e: { pc = 0x18dc4; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18a5e */
export function fn_00154(m: Machine, at = 0x00154): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00154: { pc = 0x18a5e; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18764 */
export function fn_0015a(m: Machine, at = 0x0015a): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0015a: { pc = 0x18764; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x19366 */
export function fn_00160(m: Machine, at = 0x00160): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00160: { pc = 0x19366; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1939c */
export function fn_00166(m: Machine, at = 0x00166): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00166: { pc = 0x1939c; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x193da */
export function fn_0016c(m: Machine, at = 0x0016c): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0016c: { pc = 0x193da; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x13e94 */
export function fn_00172(m: Machine, at = 0x00172): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00172: { pc = 0x13e94; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14a36 */
export function fn_00178(m: Machine, at = 0x00178): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00178: { pc = 0x14a36; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14578 */
export function fn_0017e(m: Machine, at = 0x0017e): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0017e: { pc = 0x14578; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14772 */
export function fn_00184(m: Machine, at = 0x00184): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00184: { pc = 0x14772; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1485c */
export function fn_0018a(m: Machine, at = 0x0018a): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0018a: { pc = 0x1485c; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14b8a */
export function fn_00190(m: Machine, at = 0x00190): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00190: { pc = 0x14b8a; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14c3c */
export function fn_00196(m: Machine, at = 0x00196): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00196: { pc = 0x14c3c; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14d48 */
export function fn_0019c(m: Machine, at = 0x0019c): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0019c: { pc = 0x14d48; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x15064 */
export function fn_001a2(m: Machine, at = 0x001a2): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001a2: { pc = 0x15064; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x155a0 */
export function fn_001a8(m: Machine, at = 0x001a8): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001a8: { pc = 0x155a0; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x15672 */
export function fn_001ae(m: Machine, at = 0x001ae): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001ae: { pc = 0x15672; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1568e */
export function fn_001b4(m: Machine, at = 0x001b4): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001b4: { pc = 0x1568e; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x156ac */
export function fn_001ba(m: Machine, at = 0x001ba): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001ba: { pc = 0x156ac; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x160ba */
export function fn_001c0(m: Machine, at = 0x001c0): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001c0: { pc = 0x160ba; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18e66 */
export function fn_001ca(m: Machine, at = 0x001ca): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001ca: { pc = 0x18e66; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x190f6 */
export function fn_001d0(m: Machine, at = 0x001d0): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001d0: { pc = 0x190f6; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x19032 */
export function fn_001d6(m: Machine, at = 0x001d6): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001d6: { pc = 0x19032; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x19010 */
export function fn_001dc(m: Machine, at = 0x001dc): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001dc: { pc = 0x19010; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18cce */
export function fn_001e2(m: Machine, at = 0x001e2): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001e2: { pc = 0x18cce; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x193c6 */
export function fn_001e8(m: Machine, at = 0x001e8): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001e8: { pc = 0x193c6; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1890c */
export function fn_001ee(m: Machine, at = 0x001ee): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001ee: { pc = 0x1890c; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x16bc8 */
export function fn_001f4(m: Machine, at = 0x001f4): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001f4: { pc = 0x16bc8; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x13f40 */
export function fn_001fa(m: Machine, at = 0x001fa): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x001fa: { pc = 0x13f40; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x13f60 */
export function fn_00200(m: Machine, at = 0x00200): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00200: { pc = 0x13f60; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x13f98 */
export function fn_00206(m: Machine, at = 0x00206): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00206: { pc = 0x13f98; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1418a */
export function fn_0020c(m: Machine, at = 0x0020c): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0020c: { pc = 0x1418a; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14044 */
export function fn_00212(m: Machine, at = 0x00212): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00212: { pc = 0x14044; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14104 */
export function fn_00218(m: Machine, at = 0x00218): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00218: { pc = 0x14104; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14138 */
export function fn_0021e(m: Machine, at = 0x0021e): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0021e: { pc = 0x14138; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x141c4 */
export function fn_00224(m: Machine, at = 0x00224): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00224: { pc = 0x141c4; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x141d4 */
export function fn_0022a(m: Machine, at = 0x0022a): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0022a: { pc = 0x141d4; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x14230 */
export function fn_00230(m: Machine, at = 0x00230): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00230: { pc = 0x14230; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1a0cc */
export function fn_00236(m: Machine, at = 0x00236): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00236: { pc = 0x1a0cc; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x19f3e */
export function fn_0023c(m: Machine, at = 0x0023c): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0023c: { pc = 0x19f3e; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1684c */
export function fn_00242(m: Machine, at = 0x00242): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00242: { pc = 0x1684c; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18b76 */
export function fn_00248(m: Machine, at = 0x00248): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00248: { pc = 0x18b76; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18b26 */
export function fn_0024e(m: Machine, at = 0x0024e): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0024e: { pc = 0x18b26; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x18b5c */
export function fn_00254(m: Machine, at = 0x00254): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00254: { pc = 0x18b5c; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x190da */
export function fn_0025a(m: Machine, at = 0x0025a): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x0025a: { pc = 0x190da; break; } break;
      default: call(pc, m); return;
    }
  }
}

/** trampoline to 0x1908a */
export function fn_00260(m: Machine, at = 0x00260): void {
  let pc = at;
  for (;;) {
    m.tick();
    switch (pc) {
      case 0x00260: { pc = 0x1908a; break; } break;
      default: call(pc, m); return;
    }
  }
}
