# Outputs consumed when wiring the app: copy these into k8s/values.yaml after the
# first `tofu apply` (same handshake as the BGM storage account). The FQDN and
# database/user names are deterministic, but the UAMI client_id is generated by
# Azure and must be read from here.

output "postgres_fqdn" {
  value       = azurerm_postgresql_flexible_server.main.fqdn
  description = "FQDN of the chess-tactics Postgres Flexible Server (the pod's POSTGRES_HOST)."
}

output "postgres_database_name" {
  value       = azurerm_postgresql_flexible_server_database.main.name
  description = "Application database name inside the Flexible Server (the pod's POSTGRES_DATABASE)."
}

output "app_identity_name" {
  value       = azurerm_user_assigned_identity.app.name
  description = "Name of the app UAMI = the Postgres login user (the pod's POSTGRES_USER)."
}

output "app_identity_client_id" {
  value       = azurerm_user_assigned_identity.app.client_id
  description = "client_id of chess-tactics-identity. Pin into k8s/values.yaml serviceAccountClientId; the app SA annotation azure.workload.identity/client-id uses it."
}
